GET http://localhost:8081/comments

###

POST http://localhost:8081/comments
Content-Type: application/json

{
    "name" : "z",
    "body" : "z",
    "mail" : "z"
}


###

DELETE http://localhost:8081/comments/1

###

PATCH  http://localhost:8081/comments/1
Content-Type: application/json

{
    "name": "nana",
    "body": "small",
    "mail": "nana@gmail.com"
}